project:
  type: website
  output-dir: _site
  resources:
    - V1/Assets/          # include only these assets in the final site
    - V1/Scripts/
    - OD_maps/temp_maps/
  render: 
    - data_alert.qmd
    - index.qmd
    - country-index.qmd
    - centralamericamexico.qmd
    - caribbean.qmd
    - southamerica.qmd
    - europemiddleeastnorthafrica.qmd
    - sub-saharanafrica.qmd
    - southasia.qmd
    - eastsoutheastasia.qmd
    - pacificislands.qmd
    - methods.qmd
    - about.qmd
    - data.qmd
 
  
website:
  navbar:
    logo: V1/Assets/logo.png
    title: "Global Dengue Observatory"
    right:
      - text: "Home"
        href: index.qmd
      - text: "All Countries"
        href: country-index.qmd
      - text: "Regions"
        menu: 
          - text: "North & Central America"         
            href: centralamericamexico.qmd
          - text: "Caribbean"                       
            href: caribbean.qmd
          - text: "South America"
            href: southamerica.qmd
          - text: "Europe, Middle East & North Africa" 
            href: europemiddleeastnorthafrica.qmd
          - text: "Sub-Saharan Africa"    
            href: sub-saharanafrica.qmd
          - text: "South Asia"
            href: southasia.qmd
          - text:  "East & Southeast Asia"
            href: eastsoutheastasia.qmd
          - text: "Pacific Islands"  
            href: pacificislands.qmd
      - text: "Methods"
        href: methods.qmd
      - text: "Data"
        href: data.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/DengueGlobalObservatory/DENV_global_observatory
  page-footer:
    center: "Â© 2025 LSHTM Global Dengue Observatory"

format:
  html:
    theme: minty
    css: style.css
    include-after-body:
      - scrollama.js
    toc: false
    toc-depth: 3
    page-layout: full
    embed-resources: true
    self-contained: false

filters:
  - quarto

    
    
                   
          
           
