project:
  type: website
  output-dir: _site
  resources:
    - V1/Assets/          # include only these assets in the final site
    - V1/Scripts/
    - OD_maps/temp_maps/
  render: 
    - index.qmd
    - pages/country-index.qmd
    - pages/centralamericamexico.qmd
    - pages/caribbean.qmd
    - pages/southamerica.qmd
    - pages/europemiddleeastnorthafrica.qmd
    - pages/sub-saharanafrica.qmd
    - pages/southasia.qmd
    - pages/eastsoutheastasia.qmd
    - pages/pacificislands.qmd
    - pages/methods.qmd
    - pages/about.qmd
    - pages/data.qmd
 
  
website:
  navbar:
    logo: V1/Assets/logo.png
    title: "Global Dengue Observatory"
    right:
      - text: "Home"
        href: index.qmd
      - text: "All Countries"
        href: pages/country-index.qmd
      - text: "Regions"
        menu: 
          - text: "North & Central America"         
            href: pages/centralamericamexico.qmd
          - text: "Caribbean"                       
            href: pages/caribbean.qmd
          - text: "South America"
            href: pages/southamerica.qmd
          - text: "Europe, Middle East & North Africa" 
            href: pages/europemiddleeastnorthafrica.qmd
          - text: "Sub-Saharan Africa"    
            href: pages/sub-saharanafrica.qmd
          - text: "South Asia"
            href: pages/southasia.qmd
          - text:  "East & Southeast Asia"
            href: pages/eastsoutheastasia.qmd
          - text: "Pacific Islands"  
            href: pages/pacificislands.qmd
      - text: "Methods"
        href: pages/methods.qmd
      - text: "Data"
        href: pages/data.qmd
      - text: "About"
        href: pages/about.qmd
      - icon: github
        href: https://github.com/DengueGlobalObservatory/DENV_global_observatory
  page-footer:
    center: "Â© 2025 LSHTM Global Dengue Observatory"

format:
  html:
    theme: minty
    css: style.css
    include-after-body:
      - scrollama.js
    toc: false
    toc-depth: 3
    page-layout: full
    embed-resources: true
    self-contained: true

filters:
  - quarto

    
    
                   
          
           
